version: '3.8'

services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'  # Certifique-se de que WWWGROUP é um número válido
    image: sail-8.3/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-13500}:80'  # Porta padrão 13500
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'  # Porta para Vite
    environment:
      WWWUSER: '${WWWUSER}'  # Usuário do ambiente
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'  # Modo do Xdebug
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'  # Configuração do Xdebug
      IGNITION_LOCAL_SITES_PATH: '${PWD}'  # Caminho local
    volumes:
      - '.:/var/www/html'  # Monta o diretório atual no contêiner
    networks:
      - sail
    depends_on:
      - mysql  # Dependência do serviço MySQL

  mysql:
    image: 'mysql/mysql-server:8.0'  # Imagem do MySQL
    ports:
      - '${FORWARD_DB_PORT:-8080}:80'  # Porta padrão 8080
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'  # Senha do root
      MYSQL_ROOT_HOST: '%'  # Permite acesso de qualquer host
      MYSQL_DATABASE: '${DB_DATABASE}'  # Nome do banco de dados
      MYSQL_USER: '${DB_USERNAME}'  # Nome do usuário
      MYSQL_PASSWORD: '${DB_PASSWORD}'  # Senha do usuário
      MYSQL_ALLOW_EMPTY_PASSWORD: 1  # Permite senha vazia
    volumes:
      - 'sail-mysql:/var/lib/mysql'  # Volume para persistência de dados
      - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'  # Script de inicialização
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'  # Teste de saúde do MySQL
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge  # Driver de rede

volumes:
  sail-mysql:
    driver: local  # Driver de volume